### ISSUE TITLE
modules directory vendored in?

### ISSUE THREAD

**Issue by wyardley** [Cosaquee/gradle#1]
This looks like an improvement over
https://github.com/gini/puppet-gradle

Just curious, though, is it intentional that the `modules` directory is checked in? Wouldn't this essentially vendor the required modules?

**Comment by wyardley** [comment]
See also #2

**Comment by Cosaquee** [comment]
#2 merged. Checking in `modules` directory was a mistake, and I`m  really embarrassed that i made such low quality module.
